/*
 MuseSpryTabSet.js - version 0.9 - Spry Pre-Release 1.7

 Copyright (c) 2010. Adobe Systems Incorporated.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice,
 this list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 Neither the name of Adobe Systems Incorporated nor the names of its
 contributors may be used to endorse or promote products derived from this
 software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 POSSIBILITY OF SUCH DAMAGE.
*/
(function(){if(typeof Spry=="undefined"||!Spry.Widget||!Spry.Widget.Base)alert("MuseSpryTabSet.js requires MuseSpryCommon.js!");else{if(!Spry.Widget)Spry.Widget={};Spry.Widget.TabbedPanels2=function(a,b){this.element=this.getElement(a);this.cgObj=this.tgObj=this.widgetRoot=null;this.setOptions(this,Spry.Widget.TabbedPanels2.config);this.setOptions(this,b);this.tabsAfterContent=this.tabsPosition=="bottom"||this.tabsPosition=="right"?!0:!1;this.initializePlugIns(Spry.Widget.TabbedPanels2.config.plugIns,
b);var c=new Spry.Widget.Event(this);this.notifyObservers("onPreInitialize",c);c.performDefaultAction&&(this.transformMarkup(),this.attachBehaviors(),this.notifyObservers("onPostInitialize",c))};Spry.Widget.TabbedPanels2.config={defaultTab:0,event:"click",hideHeader:!0,tabsPosition:"top",autoPlay:!1,displayInterval:5E3,stopOnUserAction:!0,injectionType:"replace",tabSelector:"h1,h2,h3,h4,h5,h6",contentDelimiterSelector:null,widgetClass:"TabbedPanels",tabClass:"TabbedPanelsTab",contentClass:"TabbedPanelsContent",
tabHoverClass:"TabbedPanelsTabHover",tabSelectedClass:"TabbedPanelsTabSelected",tabFocusedClass:"TabbedPanelsTabFocused",panelVisibleClass:"TabbedPanelsContentVisible",groupClassStr:"Group",firstClassStr:"First",lastClassStr:"Last",plugIns:[],sliceMap:{},classToRemove:"",classToAdd:"",enableKeyboardNavigation:!0};Spry.Widget.TabbedPanels2.prototype=new Spry.Widget.Base;Spry.Widget.TabbedPanels2.prototype.constructor=Spry.Widget.TabbedPanels2;Spry.Widget.TabbedPanels2.prototype.transformMarkup=function(){var a=
new Spry.Widget.Event(this);this.notifyObservers("onPreTransformMarkup",a);if(a.performDefaultAction){var b=Spry.$$(this.tabSelector,this.element),c=this.contentDelimiterSelector;if(!c)c=this.tabSelector;c=Spry.$$(c,this.element);b.length!=c.length&&alert("SpryTabbedPanels2.js - WARNING: Mismatch between tab elements and content delimiters!");if(b.length==0)alert("SpryTabbedPanels2.js - ERROR: Failed to find tab markup.");else{var d=this.createOptionalSlicedStructure(null,"div",this.widgetClass);
if(this.widgetID)d.id=this.widgetID;this.tgObj=this.createOptionalSlicedStructure(null,"div",this.tabClass+this.groupClassStr);for(var e=b.length,f=e-1,g=0;g<e;g++){var i=this.createOptionalSlicedStructure(null,"div",this.tabClass),h=this.getElementText(b[g]),j=document.createElement("a");j.href="#";j.appendChild(document.createTextNode(h));i.contentContainer.appendChild(j);g==0&&this.addClassName(i,this.tabClass+this.firstClassStr);g==f&&this.addClassName(i,this.tabClass+this.lastClassStr);this.tgObj.contentContainer.appendChild(i);
if(b[g].id)i.id=b[g].id,b[g].removeAttribute("id");h=parseInt(b[g].getAttribute("tabIndex"));if(!isNaN(h))i.tabIndex=b[g].tabIndex,b[g].removeAttribute("tabindex");if(this.hideHeader)b[g].style.display="none"}this.cgObj=this.createOptionalSlicedStructure(null,"div",this.contentClass+this.groupClassStr);for(g=0;g<c.length;g++){b=this.createOptionalSlicedStructure(null,"div",this.contentClass);this.cgObj.contentContainer.appendChild(b);e=c[g];for(f=c[g+1];e&&e!=f;)i=e.nextSibling,b.contentContainer.appendChild(e),
e=i;if(this.hideHeader)c[g].style.display="none"}for(;this.element.firstChild;)this.element.removeChild(this.element.firstChild);this.tabsAfterContent?(d.contentContainer.appendChild(this.cgObj),d.contentContainer.appendChild(this.tgObj)):(d.contentContainer.appendChild(this.tgObj),d.contentContainer.appendChild(this.cgObj));this.injectionType=="replace"?(this.element.parentNode.replaceChild(d,this.element),this.element=d):(this.element.innerHTML="",this.element.appendChild(d));this.widgetRoot=d;
this.tabsPosition=="bottom"&&this.addClassName(this.widgetRoot,"BTabbedPanels");if(this.tabsPosition=="left"||this.tabsPosition=="right")this.removeClassName(this.widgetRoot,"TabbedPanels"),this.addClassName(this.widgetRoot,"VTabbedPanels");this.classToRemove&&this.removeClassName(this.widgetRoot,this.classToRemove);this.classToAdd&&this.addClassName(this.widgetRoot,this.classToAdd);this.notifyObservers("onPostTransformMarkup",a)}}};Spry.Widget.TabbedPanels2.prototype.getElementText=function(a){for(var b=
[],a=a.firstChild;a;){if(a.nodeType==3||a.nodeType==4)b.push(a.data);else if(a.firstChild){var c=this.getElementText(a);c&&b.push(c)}a=a.nextSibling}return b.join("")};Spry.Widget.TabbedPanels2.prototype.getTabs=function(){var a=[];this.element&&this.tgObj&&this.tgObj.contentContainer&&(a=this.getElementChildren(this.tgObj.contentContainer));return a};Spry.Widget.TabbedPanels2.prototype.getContentPanels=function(){var a=[];this.element&&this.cgObj&&this.cgObj.contentContainer&&(a=this.getElementChildren(this.cgObj.contentContainer));
return a};Spry.Widget.TabbedPanels2.prototype.getTabbedPanelCount=function(){return Math.min(this.panelSelector.getButtonCount(),this.panelSet.getPanelCount())};Spry.Widget.TabbedPanels2.prototype.getTabIndex=function(a){return this.panelSelector.elementToIndex(a)};Spry.Widget.TabbedPanels2.prototype.getCurrentTabIndex=function(){return this.panelSelector.getCurrentButtonIndex()};Spry.Widget.TabbedPanels2.prototype.showPanel=function(a){this.panelSelector.handleActivate(a)};Spry.Widget.TabbedPanels2.prototype.showPreviousPanel=
function(){this.panelSelector.selectPreviousButton()};Spry.Widget.TabbedPanels2.prototype.showNextPanel=function(){this.panelSelector.selectNextButton()};Spry.Widget.TabbedPanels2.prototype.showFirstPanel=function(){this.panelSelector.selectFirstButton()};Spry.Widget.TabbedPanels2.prototype.showLastPanel=function(){this.panelSelector.selectLastButton()};Spry.Widget.TabbedPanels2.prototype.markOpenPanel=function(a){for(var b=this.panelSet.getPanels(),c=0;c<b.length;c++){var d=b[c];if(a==d)this.addClassName(d,
this.panelVisibleClass),d.style.display="block";else if(!this.hasClassName(d,"wrap"))this.removeClassName(d,this.panelVisibleClass),d.style.display="none"}};Spry.Widget.TabbedPanels2.prototype.attachBehaviors=function(){var a=new Spry.Widget.Event(this);this.notifyObservers("onPreAttachBehaviors",a);a.performDefaultAction&&(this.attachViewBehaviors(),this.attachTabBehaviors(),this.notifyObservers("onPostAttachBehaviors",a))};Spry.Widget.TabbedPanels2.prototype.attachViewBehaviors=function(){var a=
new Spry.Widget.Event(this);this.notifyObservers("onPreAttachViewBehaviors",a);if(a.performDefaultAction){var b=this.getContentPanels();this.panelSet=new Spry.Widget.PanelSet(b,{defaultPanel:this.defaultTab,autoPlay:this.autoPlay,displayInterval:this.displayInterval,visibleClass:this.panelVisibleClass});var c=this;this.panelSet.addObserver({onPostShowPanel:function(a,b){c.markOpenPanel(b.target)}});(b=this.panelSet.getCurrentPanel())&&this.markOpenPanel(b);this.notifyObservers("onPostAttachViewBehaviors",
a)}};Spry.Widget.TabbedPanels2.prototype.attachTabBehaviors=function(){var a=new Spry.Widget.Event(this);this.notifyObservers("onPreAttachTabBehaviors",a);if(a.performDefaultAction){var b=this.getTabs();this.panelSelector=new Spry.Widget.PanelSelector(b,this.panelSet,{event:this.event,selectionStopsSlideShow:this.stopOnUserAction,defaultButton:this.defaultTab,selectedClass:this.tabSelectedClass,focusedClass:this.tabFocusedClass,hoverClass:this.tabHoverClass});this.notifyObservers("onPostAttachTabBehaviors",
a)}}}})();Muse.Plugins.TabSet=function(){};Muse.Plugins.TabSet.prototype.initialize=function(a){a.observers.push(this)};
Muse.Plugins.TabSet.prototype.onPreTransformMarkup=function(a,b){if(Spry.Utils.hasClassName(a.element,"TabbedPanelsWidget")){b.preventDefault();a.tgObj=Spry.$$("."+a.tabClass+a.groupClassStr,a.element)[0];a.tgObj.contentContainer=a.tgObj;var c=Spry.$$("."+a.tabClass,a.tgObj);a.cgObj=Spry.$$("."+a.contentClass+a.groupClassStr,a.element)[0];a.cgObj.contentContainer=a.cgObj;Spry.$$("."+a.contentClass,a.cgObj);for(var d=c.length,e=d-1,f=0;f<d;f++){var g=c[f];f==0&&Spry.Utils.addClassName(g,a.tabClass+
a.firstClassStr);f==e&&Spry.Utils.addClassName(g,a.tabClass+a.lastClassStr)}}};Spry.Widget.TabbedPanels2.config.plugIns.push(new Muse.Plugins.TabSet);
